// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 2bb00f724bf705df9c7ba9fe37e96b76b5434b4f8ea1c408dc2ce9307f23aa48
import { customTools } from "./custom-tools";
import { getWeather as tool0 } from "./get-weather/tool";
import { retrieveUrl as tool1 } from "./retrieve-url/tool";
import { wordCount as tool2 } from "./word-count/tool";

const installed = {
  getWeather: tool0,
  retrieveUrl: tool1,
  wordCount: tool2,
};
for (const key of Object.keys(customTools)) {
  if (Object.hasOwn(installed, key)) {
    throw new Error(`Duplicate tool registration: ${key}`);
  }
}
export const tools = { ...installed, ...customTools };
