// Generated by chat-js sync. Put custom registrations in custom-tools.ts / custom-ui.ts.
// Content: 997ea7690c02db31deccde37399d5844ec417211625f2f4c19da1b2b579d12bc
import type { ToolRendererRegistry } from "@/lib/ai/tool-renderer-registry";
import { customUi } from "./custom-ui";
import { GetWeatherRenderer as renderer0 } from "./get-weather/renderer";
import { RetrieveUrlRenderer as renderer1 } from "./retrieve-url/renderer";
import { WordCountRenderer as renderer2 } from "./word-count/renderer";

const installed = {
  "tool-getWeather": renderer0,
  "tool-retrieveUrl": renderer1,
  "tool-wordCount": renderer2,
};
for (const key of Object.keys(customUi)) {
  if (Object.hasOwn(installed, key)) {
    throw new Error(`Duplicate renderer registration: ${key}`);
  }
}
export const ui = { ...installed, ...customUi } satisfies ToolRendererRegistry;
